services:
  db:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: ghcr.io/ei-sugimoto/tatekae/api:latest
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASS=password
      - DB_NAME=mydb
      - DB_PORT=3306
    depends_on:
      db:
        condition: service_healthy
    tty: true

  web:
    # image: ghcr.io/ei-sugimoto/tatekae/web:latest
    image: myweb:latest
    ports:
      - "3000:80"
    volumes:
      - ./web:/workspace
    depends_on:
      - api
      - db
    tty: true
    working_dir: /workspace/app
    stdin_open: true

volumes:
  db:
