services:
  db:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    image: api-image:latest
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASS=password
      - DB_NAME=mydb
      - DB_PORT=3306
    depends_on:
      db:
        condition: service_healthy
    tty: true

  web:
    image: web-image:latest
    # image: myweb:latest
    ports:
      - "3000:80"
    volumes:
      - ./web:/workspace
    depends_on:
      - api
      - db
    tty: true
    working_dir: /workspace/app
    stdin_open: true
  
  # tunnelweb:
  #   image: cloudflare/cloudflared:latest
  #   network_mode: host
  #   command:
  #     - tunnel
  #     - --no-autoupdate
  #     - run
  #   environment:
  #     - TUNNEL_TOKEN=xxx
    
  # tunnelapi:
  #   image: cloudflare/cloudflared:latest
  #   network_mode: host
  #   command:
  #     - tunnel
  #     - --no-autoupdate
  #     - run
  #   environment:
  #     - TUNNEL_TOKEN=xxx
volumes:
  db:
