FROM  golang:1.23.1-bullseye

WORKDIR /app

EXPOSE 8080

COPY . .

RUN go env -w GOPROXY=https://goproxy.io,direct && go mod download

RUN go install github.com/air-verse/air@latest

CMD ["air", "-c", ".air.toml"]