name: major

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  tag:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write # タグ作成のために必要な権限を付与
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Create new major version tag
        uses: anothrNick/github-tag-action@1.39.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: major
          RELEASE_BRANCHES: .*
          WITH_V: true
      - name: Set environment variable
        run: echo "NEW_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV
