FROM node:lts-slim AS builder

RUN npm install -g bun


COPY . /workspace

WORKDIR /workspace/app

RUN bun install


RUN bun run build

FROM nginx

# Nginx の設定ファイルを削除して、カスタム設定を利用
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

# ビルドしたファイルを Nginx の公開ディレクトリにコピー
COPY --from=builder /workspace/app/dist /usr/share/nginx/html

# コンテナを公開するポート
EXPOSE 80

ENV VITE_API_URL=http://api:8080

# Nginx を起動
CMD ["sh", "-c", "nginx -g 'daemon off;'"]